replicaCount: 2
image:
  repository: docker.io/fabulousjeff2009/cloudopshub-backend
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
database:
  enabled: false
  existingSecret: cloudopshub-rds-secret
  hostKey: DB_HOST
  portKey: DB_PORT
  nameKey: DB_NAME
  userKey: DB_USER
  passwordKey: DB_PASSWORD
