apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ include "backend.name" . }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.database.enabled }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | quote }}
                  key: {{ .Values.database.hostKey | quote }}
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | quote }}
                  key: {{ .Values.database.portKey | quote }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | quote }}
                  key: {{ .Values.database.nameKey | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | quote }}
                  key: {{ .Values.database.userKey | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | quote }}
                  key: {{ .Values.database.passwordKey | quote }}
          {{- end }}
          ports:
            - containerPort: 8080
