fullnameOverride: cloudopshub-monitoring

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}

alertmanager:
  enabled: true
  service:
    type: ClusterIP

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true
