image:
  repository: docker.io/fabulousjeff2009/cloudopshub-db
  tag: "latest"
  pullPolicy: IfNotPresent
postgres:
  database: cloudopshub
  user: cloudopshub
  password: change-me
storage:
  size: 10Gi
service:
  type: ClusterIP
  port: 5432
