image:
  repository: docker.io/fabulousjeff2009/cloudopshub-db
  tag: "latest"
  pullPolicy: IfNotPresent
postgres:
  database: cloudopshub
  user: cloudopshub
  existingSecret: cloudopshub-db-secret
  passwordKey: postgres-password
storage:
  size: 10Gi
service:
  type: ClusterIP
  port: 5432
