apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Smartflix/Deployment-of-Multi-Cluster-Infrastructure-Platform-with-Continuous-Delivery-and-Observability.git'
    targetRevision: HEAD
    path: k8s/helm/backend
    helm:
      parameters:
        - name: database.enabled
          value: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudopshub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
