apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Smartflix/Deployment-of-Multi-Cluster-Infrastructure-Platform-with-Continuous-Delivery-and-Observability.git'
    targetRevision: fix-push
    path: k8s/helm/frontend
    helm:
      parameters:
        - name: image.tag
          value: 759e34ddb88b085b65db1c0d06d571b34198435f
        - name: ingress.enabled
          value: "true"
        - name: ingress.tls.enabled
          value: "true"
        - name: ingress.tls.certificateArn
          value: arn:aws:acm:us-east-1:867041163440:certificate/dbf536a5-99ec-4ef2-89df-a70124e318c3
        - name: ingress.tls.sslRedirect
          value: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudopshub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
