replicaCount: 2
image:
  repository: docker.io/fabulousjeff2009/cloudopshub-frontend
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
  tls:
    enabled: false
    certificateArn: ""
    sslRedirect: true
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
